#!groovy

organizationFolder('example') {
    description('This contains branch source jobs for Bitbucket and GitHub')
    displayName('Organization Folder')
  	orphanedItemStrategy {
		daysToKeep((Integer)0)
		numToKeep((Integer)0)
	}
	organizations {
		github {
			repoOwner('jcpowermac')
			scanCredentialsId('github')
			pattern('(playbook2image\b)?')
			checkoutCredentialsId('github')
			buildOriginBranch(true)
			buildOriginBranchWithPR(true)
			buildOriginPRMerge(false)
			buildOriginPRHead(false)
			buildForkPRMerge(true)
			buildForkPRHead(false)
		}
    }
    triggers {
        periodic(10)
    }
}
